drop table Cls cascade constraints;
drop table DeletedObjects cascade constraints;
drop sequence SSpecialization;
drop table Specialization cascade constraints;
drop table Association cascade constraints;
drop table Association3 cascade constraints;
drop sequence SPrdcrLst;
drop table PrdcrLst cascade constraints;
drop sequence SSrvr;
drop table Srvr cascade constraints;
drop sequence SCrtPrdctGrpCMD;
drop table CrtPrdctGrpCMD cascade constraints;
drop sequence SCrtPrdcrCMD;
drop table CrtPrdcrCMD cascade constraints;
drop sequence SCspgCMD;
drop table CspgCMD cascade constraints;
drop sequence SCmmndCrdntr;
drop table CmmndCrdntr cascade constraints;
drop sequence SPrdcr;
drop table Prdcr cascade constraints;
drop sequence SAddArtclCMD;
drop table AddArtclCMD cascade constraints;
drop sequence SArtclStt;
drop table ArtclStt cascade constraints;
drop sequence SCmpnntLst;
drop table CmpnntLst cascade constraints;
drop sequence SCmpnnt;
drop table Cmpnnt cascade constraints;
drop sequence SCmmnDt;
drop table CmmnDt cascade constraints;
drop sequence SCmmndExctr;
drop table CmmndExctr cascade constraints;
drop sequence SPrdcrLstCurrProd;
drop table PrdcrLstCurrProd cascade constraints;
drop sequence SPrdctGrpCmpnnts;
drop table PrdctGrpCmpnnts cascade constraints;
drop sequence SCmmndCrdntrExctr;
drop table CmmndCrdntrExctr cascade constraints;
drop sequence SCmpnntLstCurrComps;
drop table CmpnntLstCurrComps cascade constraints;
drop sequence SCmmndExctrCommands;
drop table CmmndExctrCommands cascade constraints;
