drop table Cls cascade constraints;
drop table DeletedObjects cascade constraints;
drop sequence SSpecialization;
drop table Specialization cascade constraints;
drop table Association cascade constraints;
drop table Association3 cascade constraints;
drop sequence SCspgCMD;
drop table CspgCMD cascade constraints;
drop sequence SSrvr;
drop table Srvr cascade constraints;
drop sequence SCrtArtclCMD;
drop table CrtArtclCMD cascade constraints;
drop sequence SCstmrDlvrTm;
drop table CstmrDlvrTm cascade constraints;
drop sequence SCmmndCrdntr;
drop table CmmndCrdntr cascade constraints;
drop sequence SQntfdArtcl;
drop table QntfdArtcl cascade constraints;
drop sequence SCmpnnt;
drop table Cmpnnt cascade constraints;
drop sequence SCstmrAccnt;
drop table CstmrAccnt cascade constraints;
drop sequence SAbstrctOrdr;
drop table AbstrctOrdr cascade constraints;
drop sequence SPrdcr;
drop table Prdcr cascade constraints;
drop sequence SShppngCrt;
drop table ShppngCrt cascade constraints;
drop sequence SArtclStt;
drop table ArtclStt cascade constraints;
drop sequence SCmmnDt;
drop table CmmnDt cascade constraints;
drop sequence SArtclWrppr;
drop table ArtclWrppr cascade constraints;
drop sequence SCmmndExctr;
drop table CmmndExctr cascade constraints;
drop sequence SPrdctGrpCmpnnts;
drop table PrdctGrpCmpnnts cascade constraints;
drop sequence SCmmndCrdntrExctr;
drop table CmmndCrdntrExctr cascade constraints;
drop sequence SAbstrctOrdrArtcls;
drop table AbstrctOrdrArtcls cascade constraints;
drop sequence SShppngCrtArtcls;
drop table ShppngCrtArtcls cascade constraints;
drop sequence SCmmndExctrCommands;
drop table CmmndExctrCommands cascade constraints;
