
package model.visitor;

public interface CommandVisitor extends ArticleCommandVisitor,CustomerAccountCommandVisitor,CustomerOrderManagerCommandVisitor,CustomerRegisterServiceCommandVisitor,ProducerLstCommandVisitor,ReOrderManagerCommandVisitor,ReturnManagerCommandVisitor,ShopCommandVisitor,ShoppingCartCommandVisitor,ShoppingCartQuantifiedArticleCommandVisitor{
    
    
}
