
package model.visitor;

public interface CommandVisitor extends ArticleCommandVisitor,ComponentCommandVisitor,ComponentContainerCommandVisitor,CustomerAccountCommandVisitor,CustomerDeliveryTimeManagerCommandVisitor,CustomerOrderManagerCommandVisitor,CustomerRegisterServiceCommandVisitor,ProducerLstCommandVisitor,ReOrderManagerCommandVisitor,ReturnManagerCommandVisitor,ShoppingCartCommandVisitor,ShoppingCartQuantifiedArticleCommandVisitor{
    
    
}
