
package model.visitor;

public interface CommandVisitor extends ArticleCommandVisitor,ArticleWrapperCommandVisitor,CustomerAccountCommandVisitor,CustomerDeliveryTimeManagerCommandVisitor,CustomerOrderManagerCommandVisitor,CustomerRegisterServiceCommandVisitor,ProducerLstCommandVisitor,ProductGroupCommandVisitor,ReOrderManagerCommandVisitor,ReturnManagerCommandVisitor,ShoppingCartCommandVisitor,ShoppingCartQuantifiedArticleCommandVisitor,SubComponentCommandVisitor{
    
    
}
