
package model.visitor;

public interface CommandExceptionVisitor<E extends model.UserException> extends ArticleCommandExceptionVisitor<E>,ComponentCommandExceptionVisitor<E>,ComponentContainerCommandExceptionVisitor<E>,CustomerAccountCommandExceptionVisitor<E>,CustomerDeliveryTimeManagerCommandExceptionVisitor<E>,CustomerOrderManagerCommandExceptionVisitor<E>,CustomerRegisterServiceCommandExceptionVisitor<E>,ProducerLstCommandExceptionVisitor<E>,ReOrderManagerCommandExceptionVisitor<E>,ReturnManagerCommandExceptionVisitor<E>,ShoppingCartCommandExceptionVisitor<E>,ShoppingCartQuantifiedArticleCommandExceptionVisitor<E>{
    
    
}
