drop table IntegerValue;
drop table FractionValue;
drop table StringValue;
drop table DateValue;
drop table TimestampValue;
drop table TextValue;
drop table Lnk;
drop table Lnk3;

alter table Association drop constraint AssPK;
alter table Association3 drop constraint Ass3PK;
drop table Obj;
drop sequence SObj;
drop sequence SLnk;
drop sequence SLnk3;

drop table DeletedObjects;

alter table DeletedObjects_Old rename to DeletedObjects;
alter table DeletedObjects add constraint FDeletedObjectsInstanceOf foreign key (instanceOf) references Cls(id);
create unique index DltdObjInx on DeletedObjects (id, instanceOf);
drop view Srvr;
alter table Srvr_Old rename to Srvr;
drop view CstmrDlvrTm;
alter table CstmrDlvrTm_Old rename to CstmrDlvrTm;
drop view CmmndCrdntr;
alter table CmmndCrdntr_Old rename to CmmndCrdntr;
drop view QntfdArtcl;
alter table QntfdArtcl_Old rename to QntfdArtcl;
drop view Cmpnnt;
alter table Cmpnnt_Old rename to Cmpnnt;
drop view CstmrAccnt;
alter table CstmrAccnt_Old rename to CstmrAccnt;
drop view AbstrctOrdr;
alter table AbstrctOrdr_Old rename to AbstrctOrdr;
drop view Prdcr;
alter table Prdcr_Old rename to Prdcr;
drop view ShppngCrt;
alter table ShppngCrt_Old rename to ShppngCrt;
drop view ArtclStt;
alter table ArtclStt_Old rename to ArtclStt;
drop view CmmnDt;
alter table CmmnDt_Old rename to CmmnDt;
drop view ArtclWrppr;
alter table ArtclWrppr_Old rename to ArtclWrppr;
drop view CmmndExctr;
alter table CmmndExctr_Old rename to CmmndExctr;
drop view PrdctGrpCmpnnts;
alter table PrdctGrpCmpnnts_Old rename to PrdctGrpCmpnnts;
drop view CmmndCrdntrExctr;
alter table CmmndCrdntrExctr_Old rename to CmmndCrdntrExctr;
drop view AbstrctOrdrArtcls;
alter table AbstrctOrdrArtcls_Old rename to AbstrctOrdrArtcls;
drop view ShppngCrtArtcls;
alter table ShppngCrtArtcls_Old rename to ShppngCrtArtcls;
drop view CmmndExctrCommands;
alter table CmmndExctrCommands_Old rename to CmmndExctrCommands;
