package model.meta;

public interface GlobalOrderManagerMssgsVisitor extends GlobalOrderManagerDOWNMssgsVisitor, GlobalOrderManagerUPMssgsVisitor {}


interface GlobalOrderManagerDOWNMssgsVisitor  {

    public void handleGlobalOrderManagerHandleOrderArticlesInReturnOrderStateOrderArticlesInReturnOrderStateMssg(GlobalOrderManagerHandleOrderArticlesInReturnOrderStateOrderArticlesInReturnOrderStateMssg event) throws persistence.PersistenceException;
    public void handleGlobalOrderManagerHandleOrderInTransitOrderStateOrderInTransitOrderStateMssg(GlobalOrderManagerHandleOrderInTransitOrderStateOrderInTransitOrderStateMssg event) throws persistence.PersistenceException;
    public void handleGlobalOrderManagerHandleOrderPreOrderStateOrderPreOrderStateMssg(GlobalOrderManagerHandleOrderPreOrderStateOrderPreOrderStateMssg event) throws persistence.PersistenceException;
    public void handleGlobalOrderManagerHandleOrderWaitingForAcceptOrderStateOrderWaitingForAcceptOrderStateMssg(GlobalOrderManagerHandleOrderWaitingForAcceptOrderStateOrderWaitingForAcceptOrderStateMssg event) throws persistence.PersistenceException;
    
}


interface GlobalOrderManagerUPMssgsVisitor extends OrderManagerUPMssgsVisitor, BackgroundTaskUPMssgsVisitor {

    public void handleGlobalOrderManagerHandleOrderArticlesInReturnOrderStateOrderArticlesInReturnOrderStateMssg(GlobalOrderManagerHandleOrderArticlesInReturnOrderStateOrderArticlesInReturnOrderStateMssg event) throws persistence.PersistenceException;
    public void handleGlobalOrderManagerHandleOrderInTransitOrderStateOrderInTransitOrderStateMssg(GlobalOrderManagerHandleOrderInTransitOrderStateOrderInTransitOrderStateMssg event) throws persistence.PersistenceException;
    public void handleGlobalOrderManagerHandleOrderPreOrderStateOrderPreOrderStateMssg(GlobalOrderManagerHandleOrderPreOrderStateOrderPreOrderStateMssg event) throws persistence.PersistenceException;
    public void handleGlobalOrderManagerHandleOrderWaitingForAcceptOrderStateOrderWaitingForAcceptOrderStateMssg(GlobalOrderManagerHandleOrderWaitingForAcceptOrderStateOrderWaitingForAcceptOrderStateMssg event) throws persistence.PersistenceException;
    
}
